mainServer/blog/urls.py
from django.urls import path
from .views import PostListView,PostDetailView,PostCreateView,PostUpdateView,PostDeleteView,UserPostListView,comment,upvote,downvote,deleteComment
from . import views
urlpatterns = [
    path('', PostListView.as_view(), name='blog-home'),
    path('user/<str:username>/', UserPostListView.as_view(), name='user-posts'),
    path('post/<int:pk>', PostDetailView.as_view(), name='post-detail'),
    path('post/new/', PostCreateView.as_view(), name='post-create'),
    path('post/<int:pk>/update/', PostUpdateView.as_view(), name='post-update'),
    path('post/<int:pk>/delete/', PostDeleteView.as_view(), name='post-delete'),
    path('post/upvote/',views.upvote,name='upvote'),
    path('post/downvote/',views.downvote,name='downvote'),
    path('post/delete/<int:comment>/',views.deleteComment,name='deleteComment'),
    path('post/comment',views.comment,name='comment'),
    path('post/savecomment/',views.savecomment,name='savecomment')
]

mainServer/judge/urls.py
from django.urls import path
# from .views import problem
from .views import ProblemListView
from . import views

urlpatterns = [
    path('problems/',views.problems,name='judge'),
    
    path('problems/',views.problems,name='problem'),
    path('problems/order/',views.orderproblem,name='order'),
    path('problems/get_data',views.get_data,name='get-data'),
    path('problems/filter_tags/',views.filter_tags,name='filter_tags'),
    path('problems/filter_difficulty/<str:diff>/',views.filter_difficulty,name='filter-difficulty'),
    path('ide/',views.ide,name='ide'),
    path('ide/runcode/',views.runcode,name='runcode'),
    path('addproblem/',views.addproblem,name='addproblem'),
    path('addproblem/save/',views.save,name='save'),
    path('detail/<int:pid>/',views.detail,name='detail'),
    path('detail/<int:pid>/submit/',views.submit,name='submit'),
    path('detail/<int:pid>/solutions/',views.solutions,name='solutions'),
    path('detail/<int:pid>/solutions/<int:sid>',views.sol_detail,name='sol_detail'),
    # path('detail/<int:pid>/submit/viafile/',views.viafile,name='viafile'),
    path('detail/<int:pid>/submit/viacode/',views.viacode,name='viacode')
]

mainServer/mainServer/urls.py
"""django_project URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/3.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static
from judge.views import user_info,UsersListView,problems
urlpatterns = [
    path('admin/', admin.site.urls),
    # path('register/',user_views.register,name='register'),
    path('profile/',user_views.profile,name='profile'),
    path('users/<str:name>/',user_info,name="user-info"),
    path('users/',UsersListView.as_view(),name="users"),
    path('login/',auth_views.LoginView.as_view(template_name='users/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='users/logout.html'),name='logout'),
    path('password-reset/',auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),name='password_reset'),
    path('password-reset/done',auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>',auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),name='password_reset_confirm'),
    path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),name='password_reset_complete'),
    path('discuss/', include('blog.urls')),
    path('judge/',include('judge.urls')),
    # path('',include('home.urls')),
    path('froala_editor/', include('froala_editor.urls')),
    path('social-auth/', include('social_django.urls', namespace='social')),
    path('',problems,name="home"),
]

if settings.DEBUG:
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
#
# from django.contrib import admin
# from django.urls import path, include
# from django.contrib.auth import views as auth_views
# from mainApp import views
# urlpatterns = [
#     path('admin/', admin.site.urls),
#     path('judge/',include('judge.urls')),
#     path('login/', views.login, name='login'),
#     path('logout/', auth_views.LogoutView.as_view(), name='logout'),
#     path('social-auth/', include('social_django.urls', namespace='social')),
# ]

mainServer/judge/models.py
from django.db import models
from django.contrib.auth.models import User
from users.models import Profile
from django.utils import timezone
from froala_editor.fields import FroalaField



class Graph(models.Model):
  user = models.ForeignKey(User,on_delete=models.CASCADE)
  event = models.CharField(max_length=100)
  date = models.DateTimeField(default=timezone.now)
  local_rank = models.IntegerField()
  new_rating = models.IntegerField()
  old_rating =models.IntegerField()
  absolute = models.IntegerField()


	
class Problem(models.Model):
    title = models.CharField(max_length=100)
    statement = FroalaField(options={
    'height': 300,'lineHeights': {
      'Default': '',
      'Single': '1',
      '1.15': '1.15',
      '1.5': '1.5',
      'Double': '2'
    }
  },theme='gray',blank='true')
    constraint =FroalaField(options={
    'height': 100,'placeholderText':'e.g.,<br><ul><li>N &gt; 10<sup>9&nbsp;</sup>&nbsp;</li><li>A<sub>1</sub>+A<sub>2</sub>+........+A<sub>N</sub>&nbsp; &gt; 10<sup>18</sup></li></ul>'
  },theme='gray',blank='true')
    input_format = models.TextField()
    output_format = models.TextField()
    sample_input = models.TextField()
    sample_output = models.TextField()
    explaination = models.TextField()
    time_limit = models.IntegerField(default=1)
    difficulty = models.CharField(max_length=10)
    auth = models.ForeignKey(User,on_delete=models.CASCADE)
    date_added = models.DateTimeField(default=timezone.now)
    due_date = models.DateTimeField(default=timezone.now)
    branch = models.CharField(default="CS",max_length=10)
    year = models.IntegerField(default=1)
    input_file = models.FileField(upload_to='inputs/')
    output_file = models.FileField(upload_to='outputs/')
    difficultylevel = models.IntegerField("default=1")
    def __str__(self):
        return self.title

    def save(self,*args,**kwargs):
      if self.difficulty == "Easy":
         self.difficultylevel=1
      elif self.difficulty == "Medium":
         self.difficultylevel=2
      elif self.difficulty == "Hard":
         self.difficultylevel=3
      else :
         self.difficultylevel=4
      super().save(*args,**kwargs)


class Problem_Feature(models.Model):
    problem = models.OneToOneField(Problem,on_delete = models.CASCADE, primary_key = True)
    accuracy =  models.FloatField(default=0)
    total_submission = models.IntegerField(default=0)

class Problem_Tags(models.Model):
    problem = models.ForeignKey(Problem,on_delete = models.CASCADE)
    tags = models.CharField(max_length=20)

    def __str__(self):
        return self.tags


class Solution(models.Model):
    problem = models.ForeignKey(Problem,on_delete=models.CASCADE)
    usr = models.ForeignKey(User,on_delete=models.CASCADE)
    language = models.TextField()
    date_submitted = models.DateTimeField(default=timezone.now)
    solution_file = models.FileField(upload_to='solutions/')
    time=models.TextField(default="0")
    verdict=models.TextField(default="wa")

class Result(models.Model):
    solution = models.OneToOneField(Solution,on_delete = models.CASCADE, primary_key = True) 
    verdict = models.TextField()
    time = models.TextField()
    message = models.TextField()

mainServer/users/models.py
from django.db import models
from django.contrib.auth.models import User
from PIL import Image

class Profile(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    image = models.ImageField(default='default.jpg',upload_to='profile_pics')
    institution = models.CharField(max_length=100,default="IET")
    bio = models.TextField(default="...")
    rating=models.IntegerField(default=0)
    hrating=models.IntegerField(default=0)
    star=models.IntegerField(default=1)
    ac_solution=models.IntegerField(default=0)
    wa_solution=models.IntegerField(default=0)
    tle_solution=models.IntegerField(default=0)
    ce_solution=models.IntegerField(default=0)
    re_solution=models.IntegerField(default=0)
    
    def __str__(self):
        return f'{self.user.username} Profile'

    def save(self,*args,**kwargs):
        super().save(*args,**kwargs)
        
        img  = Image.open(self.image.path)

        if img.height > 300 or img.width > 300:
            output_size = (300,300)
            img.thumbnail(output_size)
            img.save(self.image.path)

mainServer/judge/forms.py
from django import forms
from django.forms import ModelForm
from froala_editor.widgets import FroalaEditor
from .models import Problem

class Statement(forms.ModelForm):
    class Meta:
        model = Problem
        fields = ['statement','constraint']

mainServer/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    class Meta:
        model = User
        fields = ['username','first_name','last_name','email','password1','password2']


class UserUpdateForm(forms.ModelForm):
    #email = forms.EmailField()

    class Meta:
        model = User
        fields = ['first_name','last_name']

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model=Profile
        fields = ['image']

mainServer/users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .forms import UserRegisterForm,UserUpdateForm,ProfileUpdateForm


# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(request.POST)
#         if form.is_valid():
#             form.save()
#             username = form.cleaned_data.get('username')
#             messages.success(request, f'Your account has been created! You can login now')
#             return redirect('login')
#     else:
#         form = UserRegisterForm()
#     return render(request, 'users/register.html', {'form':form} )
@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, f'You account has been update')
            return redirect('profile')
    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)       
    context = {
        'u_form': u_form,
        'p_form': p_form
    }
    return render(request,'users/profile.html',context)

mainServer/judge/templates/judge/addproblem.html
{% extends "judge/base.html" %}
{% load crispy_forms_tags %}
{% block content %}

{{ form.media }}


<main role="main" class="container">
  <div class="row">
    <div class="col-md-12">
      {% if messages %}
      {% for message in messages %}
      <div class="alert alert-{{message.tags}}">
        {{message}}
      </div>
      {% endfor %}
      {% endif %}
      <form action="save/" enctype="multipart/form-data" method="post">

        {% csrf_token %}


        <div class="form-group">

          <label for="title">Problem Title</label><br>
          <input type="text" class="form-control form-control-lg" name="title" required><br>





          {{form | crispy}}<br>

          <label for="input_format">Input format</label><br>
          <textarea autocomplete="off" rows="5" class="form-control" name="input_format"></textarea><br>

          <label for="output_format">Output format</label><br>
          <textarea autocomplete="off" rows="5" class="form-control" name="output_format"></textarea><br>

          <div class="row">
          <div class="col">
          <label for="sample_input">Sample Input</label><br>
          <textarea autocomplete="off" rows="5" style="font-family:Courier New;color:lime" class="bg-dark form-control" placeholder=">_" name="sample_input"></textarea><br>
          </div>
          <div class="col">
          <label for="sample_output">Sample Output</label><br>
          <textarea autocomplete="off" rows="5" style="font-family:Courier New;color:lime" class="bg-dark form-control" placeholder=">_" name="sample_output"></textarea><br>
          </div>
          </div>

          <label for="explaination">Explaination</label><br>
          <textarea autocomplete="off" rows="5" class="form-control" name="explaination"></textarea><br>

          <div class="card ">
          <div class="row mt-2 mb-1 p-3">
          <div class="col-4 ">
          
          <label for="time_limit">Time limit (between 1s and 3s):</label>
          <input type="number" class="btn btn-outline-secondary" name="time_limit" min="1" max="3" value="1"><br>
          </div>
          <div class="col-1"></div>
          <div class="col-3">
          <label for="difficulty">Difficulty:</label>
          <select class="btn btn-outline-secondary " name="difficulty">
            <option value="Easy">Easy</option>
            <option value="Medium">Medium</option>
            <option value="Hard">Hard</option>
            <option value="Expert">Expert</option>
          </select><br>
         </div>
         <div class="col-1"></div>
           <div class="col-3">
           
          <div class="dropup">
          <label>#Tags</label>
            <button class="btn btn-outline-secondary dropdown-toggle" type="button" id="dropdownMenuButton"
              data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Select
            </button>
            <div class="dropdown-menu border border-dark p-4 bg-light" aria-labelledby="dropdownMenuButton">

      
              <input type="checkbox" class="chk" id="dp" name="tag[]" value="DP">
              <label for="dp" class="chkt btn btn-outline-dark" >Dynamic Pro.</label><br>
             
         
              <input type="checkbox" class="chk" id="bm" name="tag[]" value="Bit-mask">
              <label for="bm" class="chkt btn btn-outline-dark">Bit-masking</label><br>
        

           
              <input type="checkbox" class="chk" id="gd" name="tag[]" value="Greedy">
              <label for="gd" class="chkt btn btn-outline-dark" >Greedy</label><br>
          

        
              <input type="checkbox" class="chk" id="gph" name="tag[]" value="Graph">
              <label for="gph" class="chkt  btn btn-outline-dark">Graph</label><br>
        

    
              <input type="checkbox" class="chk" id="dc" name="tag[]" value="Divide-Conquer">
              <label for="dc" class="chkt btn btn-outline-dark">Divide-conquer</label><br>
        
              <input type="checkbox" class="chk" id="srt" name="tag[]" value="Sorting">
              <label for="srt" class="chkt btn btn-outline-dark">Sorting</label>
            
            </div>
          </div>
          </div>
          </div>
          </div><br>
            <div class="card ">
          <div class="row mt-2 mb-1 p-3">
          <div class="col-4 ">

          <label for="year">Year:</label>
          <select class="btn btn-outline-secondary " name="year">
            <option value=1>1</option>
            <option value=2>2</option>
            <option value=3>3</option>
            <option value=4>4</option>


          </select><br>
          </div>
          <div class="col-1"></div>
          <div class="col-3">
          <label for="branch">Branch:</label>
          <select class="btn btn-outline-secondary " name="branch">
            <option value="CS">CS</option>
            <option value="IT">IT</option>
            <option value="ETC">ETC</option>
            <option value="EI">EI</option>
              <option value="CIVIL">CIVIL</option>
              <option value="MECH">MECH</option>


          </select><br>
         </div>
         <div class="col-1"></div>
           <div class="col-3">

          <div class="dropup">
          <label>Due Date</label>
              <input type="date" name="due_date" required>
            </div>
          </div>
          </div>
          </div>
          </div><br>



           <div class="card p-3">
           <div class="row">
           <div class="col">
          <label for="input_file">Select input file:</label>
          <input class="btn btn-outline-secondary" type="file" name="input_file" required><br>
          </div>
          <div class="col">
          <label for="output_file">Select output file:</label>
          <input class="btn btn-outline-secondary" type="file" name="output_file" required><br>
          </div>
          </div>
          </div>
          <br>
          <center>
          <input class="btn btn-secondary" type="submit" value="        Submit         ">
          </center>
        </div>

      </form>

      

    </div>
  </div>
</main>


{% endblock content %}

mainServer/judge/templates/judge/detail.html
{% extends "judge/base.html" %}
{% block content %}
<link href="/static/froala_editor/css/froala_style.min.css" type="text/css" media="all" rel="stylesheet">
<main role="main" class="container">
    <div class="row">
      <div class="col-md-8">
      <center><h3>{{problem.title}}</h3></center>
  <center>
  {% for tag in problem.problem_tags_set.all %}
  #{{tag}}
  {% endfor %}
  </center><br><hr>
  <div class="fr-view">
 {{ problem.statement | safe }}
</div>
<hr>
  <h4>Input</h4>
  <p class=" card-text article-content">{{problem.input_format}}</p><hr>
   <h4>Output</h4>
  <p class=" card-text article-content">{{problem.output_format}}</p><hr>
     <h4>Constraints</h4>
  <div class="fr-view">
 {{ problem.constraint | safe }}
   </div><hr>
  <h4>Example Input</h4>
  <div class="card bg-dark mb-3" style="max-width: 100%%;">
  <div class="card-body">
    <p style="font-family:Courier New;color:lime" class="card-text article-content">{{problem.sample_input}}</p>
  </div>
</div><hr>
<h4>Example Output</h4>
  <div class="card bg-dark mb-3" style="max-width: 100%%;">
  <div class="card-body">
    <p style="font-family:Courier New;color:lime" class="card-text article-content">{{problem.sample_output}}</p>
  </div>
</div><hr>
      
      <h4>Explaination</h4>
  <p class=" card-text article-content">{{problem.explaination}}</p><hr>
    {% if request.user.is_authenticated %}
          {%if faculty %}
          <center>
   <br>
   <a href="solutions/"><button class="btn btn-secondary">View Submissions</button></a>
   <div style="margin-bottom:20px">
      </div>
   </center>
          {% else %}
   <center>
   <br>
   <a href="submit/"><button class="btn btn-secondary">Submit</button></a>
   <div style="margin-bottom:20px">
      </div>
   </center>{%endif%}
          {%else%}
          <p>Please Login to Submit</p>
          {%endif%}
        
        
      </div>
      
      <div style="margin-top:100px" class="col-md-4" >
      <div class="content-section">
       <div class="row">
      <div  class="col-6">
      <p>Author:</p>
      <p>Date added:</p>
          <br>
          <p>Due Date:</p>
          <br>
      <p>Time limit:</p>
      <p>Difficulty:</p>
      <p>Memory:</p>
      <p>Languages:</p>
      </div>
      <div class="col-6">
      <p>{{problem.auth}}</p>
      <p>{{problem.date_added|date:"F d, Y"}}</p>
          <p>{{problem.due_date|date:"F d, Y"}}</p>
      <p>{{problem.time_limit}}sec.</p>
      <p>{{problem.difficulty}}</p>

<!--      <p>{{ problem.problem_feature.total_submission }}</p>-->
<!--      <p class="card-text mb-1"><div class="progress">-->
<!--      <div class="progress-bar" role="progressbar" style="color:black; width: {{ problem.problem_feature.accuracy }}%;" aria-valuenow="{{ problem.problem_feature.accuracy }}" aria-valuemin="0" aria-valuemax="100">{{ problem.problem_feature.accuracy }}%</div>-->
<!--      </div><br>-->
      <p>256 MB</p>
      <p>C ,C++ ,JAVA<br>PYTHON3</p>
      </div>

     </div>
     </div>

     <div class="content-section">
     <h5>Successful Submissions</h5>
          <small class='text-muted'>Recent successful submissions will appear here</small>
       <div class="shadow-lg p-3  bg-white rounded">
       <div class="row" >
       <div class="col-4">User</div>
       <div class="col-4">Time</div>
       <div class="col-4">Lang</div>
     </div>
       <hr>
       {% if solutions %}
       {% for solution in solutions %}
       {% if solution.result.verdict == 'ac' %}
       
       <div class="row" >
       <div class="col-4">{{solution.usr}}</div>
       <div class="col-4">{{solution.result.time}}s</div>
       <div class="col-4">{{solution.language}}</div>
       </div>
      
       {% endif %}
       {% endfor %}
       {% else %}
       <p>No accepted solutions yet</p>
       {% endif %}
       
     </div>


     </div>

  
        
        </div> 
      </div>
    </div>
  </main>





  
{% endblock content %}

mainServer/judge/templates/judge/judge.html
{% extends "judge/base.html" %}
{% block content %}

<main role="main" class="container">
   <div class="row">

   <div class="col-md-8 ">
   <h3>Trending Problems
   </h3>
    <div class="row">
  <div class="col-1" style="font-size:10px"><center>#<center></div>
  <div class="col-3" style="font-size:10px"><center>NAME</center></div>
  <div class="col-3" style="font-size:10px"><center>TAGS</center></div>
  <div class="col-1" style="font-size:10px"><center>AUTH</center></div>
  <div class="col-1" style="font-size:10px"><center>SUB.</center></div>
  <div class="col-3" style="font-size:10px"><center>ACC%</center></div>
  </div>
  <hr>

   {% for problem in problems %}
 

 <div class="shadow-lg p-3 mb-2 bg-white rounded">
  <div class="row">

  <div class="col-1" id="prob{{forloop.counter}}"></div>
<script>
 
     $('#prob{{forloop.counter}}').html($.urlParam('page')*10+{{ forloop.counter }}-10);
  </script>
  {% if problem.difficulty == "Easy" %}
  <div class="col-3"><a href="{% url 'detail' problem.id %}"><center>{{problem.title}} <span class="badge badge-success">Easy</span></center></a></div>

  {% elif problem.difficulty == "Medium" %}
  <div class="col-3"><a href="{% url 'detail' problem.id %}"><center>{{problem.title}} <span class="badge badge-info">Medium</span></center></a></div>

    {% elif problem.difficulty == "Hard" %}
  <div class="col-3"><a href="{% url 'detail' problem.id %}"><center>{{problem.title}} <span class="badge badge-warning">Hard</span></center></a></div>

   {% elif problem.difficulty == "Expert" %}
  <div class="col-3"><a href="{% url 'detail' problem.id %}"><center>{{problem.title}} <span class="badge badge-danger">Expert</span></center></a></div>
  {% endif %}


  <div class="col-3">
  
  <p>
  <a  data-toggle="collapse" href="#collapseExample{{ forloop.counter }}" role="button" aria-expanded="false" aria-controls="collapseExample">
   <center><i class="fas fa-list-ul"></i></center>

  </a>
  </p>


<div class="collapse" id="collapseExample{{ forloop.counter }}">
  <div class="card card-body">
   {% for tag in problem.problem_tags_set.all %}
   <p style="font-size:1vw">{{tag}}</p>
   {%endfor%}
  </div>
</div>

</div>

  <div class="col-1"><center>{{problem.auth}}</center></div>
  <div class="col-1"><center>{{ problem.problem_feature.total_submission }}</center></div>
  <div class="col-3"> <p class="card-text mb-1"><div class="progress">
   <div class="progress-bar text-light" role="progressbar" style="color:black; width: {{ problem.problem_feature.accuracy}}%;" aria-valuenow="{{ problem.problem_feature.accuracy }}" aria-valuemin="0" aria-valuemax="100">{{ problem.problem_feature.accuracy }}%</div>
    </div></div>
  
  </div>
  </div>
   {% endfor %}

   </div>
    <div class="col-md-4">
     
      <div class="mt-2">
        <a href="{% url 'problem' %}" ><button class="btn btn-primary form-control"><i class="fas fa-file "></i>  Problem Set</button></a>
        </div>
       <div class="mt-2">
        <a href="{% url 'addproblem' %}" ><button class="btn btn-primary form-control"><i class="fas fa-plus"></i> Add Problem</button></a>
        </div>
         <div class="mt-2 mb-2">
         <a href="{% url 'users' %}" ><button class="btn btn-primary form-control"><i class="fas fa-user"></i>  Users</button></a>
         
         </div>
        <div class="content-section">
          <h3>Contests</h3>
          <p class='text-muted'>Upcoming Events.
            <ul class="list-group">
              <li class="list-group-item list-group-item-light">CodeFiesta, Rated - August 15,2021 </li>
              <li class="list-group-item list-group-item-light">Electra,Unrated - July 30,2021</li>
              <li class="list-group-item list-group-item-light">HackItUp,Practice - Sept. 1,2021</li>
              <li class="list-group-item list-group-item-light">Reverso,Rated - Sept. 3,2021</li>
              
            </ul>
          </p>
        </div>
      </div>
      </div>
 
    





 </main>

  



  

{% endblock content %}

mainServer/judge/templates/judge/sol_detail.html
{% extends "judge/base.html" %}
{% block content %}
<link href="/static/froala_editor/css/froala_style.min.css" type="text/css" media="all" rel="stylesheet">
<main role="main" class="container">
    <pre>{{sol_file}}</pre>
  </main>





  
{% endblock content %}